urlSongCharts = "https://www.billboard.com/h/top-music-hits-world-international-song-charts/"
fileNameChartLinks = 'src/chartsBillboard.csv'
fileSongsListened = "src/songsListened.csv"
fileSongsNotListened = "src/songsNotListened.csv"
fileChartProperties = "src/chartPropertiesBillboard.csv"
fileChartCount = "chartSongCount.csv"
headerFile = "artist;songName;rank;chart;date;urlYoutube"
headerGUI = ['Artist', 'Song Name', 'Chart', 'Rank', 'Play on Youtube']
column_widths = [150, 150, 50, 50, 50, 150, 0, 0, 0, 10]
btnRanks = [10, 20, 25, 30, 40, 50, 100, 200, 500]
maxArtistLength = 20
maxSongLength = 20
MAX_SONG_COMPONENT_SIZE = 25
SCORE_NUMERATOR = 100
SCORE_DENOMINATOR = 8
SCORE_RATING_INERTIA = 10
MIN_SLEEP_BETWEEN_CHARTS = 3
MAX_SLEEP_BETWEEN_CHARTS = 5
ICON_SIZE = 50
PAGE_SIZE_SONG = 15
NO_SONGS_LAST = 20

CHART_TABLE_OFFSET_ROW = 0
CHART_TABLE_OFFSET_COLUMN = 5
SONG_TABLE_OFFSET_ROW = 3
SONG_TABLE_OFFSET_COLUMN = 0